version: '3'
services:
  nginx: 
    image: nginx:1.22-alpine
    ports:
      - "8080:80"
    volumes: 
      - ./:/code
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network
  # mailpit:
  #   image: axllent/mailpit
  #   container_name: mailpit
  #   restart: always
  #   volumes:
  #     - ./data:/data
  #   ports:
  #     - 8025:8025
  #     - 1025:1025
  #   environment:
  #     MP_MAX_MESSAGES: 5000
  #     MP_DATA_FILE: /data/mailpit.db
  #     MP_SMTP_AUTH_ACCEPT_ANY: 1
  #     MP_SMTP_AUTH_ALLOW_INSECURE: 1
  php: 
    build: .
    volumes:
      - ./:/code
    networks:
      - app-network
  mysql:
    image: mysql:8.2
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: snowtricks
      MYSQL_USER: snowtricks_user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - data:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 8081:80
    networks:
      - app-network
volumes:
  data:

networks:
  app-network:
